name: Add Artifact Link to PR

on:
  workflow_run:
    workflows: ['Build Firmware']
    types: [completed]

jobs:
  comment-action:
    runs-on: ubuntu-latest
    steps:
      - name: Link Artifacts via action
        uses: stylesuxx/link-artifacts-in-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          whitelist: "[]"
